### ISSUE TITLE
Mouse stops warping under certain circumstances involving Emacs tabs

### ISSUE THREAD

**Issue by leungbk** [ieure/exwm-mff#2]
I have two Emacs tabs open. In one tab (tab A), I have two Emacs windows horizontally split. In the other tab (B), I have one window occupying the whole frame.

Within tab A, pressing `C-x o` results in the mouse moving along with the selected window, as expected. Suppose the mouse cursor ends up in window A1. If I `tab-bar-switch-to-next-tab` to tab B and move the mouse cursor to the portion of the screen where window A2 would be back in tab A, I find that when I `tab-bar-switch-to-next-tab` again to go back to tab A, pressing `C-x o` does not warp the mouse cursor.

However, within tab A, once I move the mouse cursor between windows A1/A2, I find that the mouse cursor properly moves again according to `C-x o`.

I noticed this with either of

``` elisp
  (setq mouse-autoselect-window t
        focus-follows-mouse t
        )
```

or

``` elisp
  (setq mouse-autoselect-window nil
        focus-follows-mouse nil
        )
```

(not sure if these settings influence this package)

**Comment by ieure** [comment]
This is with the tabbar stuff built in to Emacs 27.1?

What version of exwm-mff are you using?  I recently (as in, this week) rewrote a bunch.  If you're not already, could you try with commit 2081c482d201edf4a30106a6a7df89cadf24bfd9 and let me know if that makes a difference?

**Comment by ieure** [comment]
Also, please `(setq exwm-mff--debug 1)` and paste the contents of `" *exwm-mff-debug*"` (note the space at the beginning of the name) while reproducing the behavior.

**Comment by ieure** [comment]
Closing due to no response.
